Lead-Studios/DeWordle

CONTRIBUTING.md
=> Docs: Create contributing.md

onchain/src/dewordle.cairo, onchain/tests/test_dewordle.cairo
Hi !
I've implemented the `set_daily_word` and `get_daily_word` functions and added a simple test function. Let me know if any changes are needed.
I also noticed that the `set_daily_word` function is public. Should this be restricted to the contract owner only?
Thanks!
=> add set_daily_word and get_daily_word functions with tests

backend/package-lock.json, backend/package.json, backend/src/leaderboard/entities/leaderboard.entity.ts, backend/src/result/entities/result.entity.ts, backend/src/result/enums/status.enum.ts, backend/src/users/entities/user.entity.ts, package-lock.json
- create user, result, and leaderboard entities.
=> feat: create entities for result, leaderboard and user

backend/src/auth/auth.module.ts, backend/src/auth/providers/bcrypt-provider.ts, backend/src/auth/providers/hashing-provider.ts, backend/src/users/providers/create-users-provider.ts, backend/src/users/users.controller.ts, backend/src/users/users.module.ts, backend/src/users/users.service.ts
removed dummy dto, entity and database  values
=> feat(user): implement sign-up functionality with hashed passwords

.github/workflows/smart-contract-ci.yml
This pull request introduces a comprehensive GitHub Actions workflow to automate the building, testing, and quality assurance of our Cairo smart contracts in the DeWordle project. The implementation establishes a robust continuous integration pipeline specifically designed for StarkNet contract development.
- Automated contract compilation and verification
- Standardized code formatting checks using Scarb
- Comprehensive test suite execution
- Security pattern scanning
- Artifact preservation for deployment readiness
The workflow has been carefully structured to run in an Ubuntu environment, with specific attention to the Scarb package manager integration. Environment variables and working directories are configured to ensure consistent execution across different stages of the pipeline. …
=> feat(ci): Add GitHub Workflow for Smart Contract Automation

backend/package-lock.json, backend/package.json, backend/src/auth/auth.module.ts, backend/src/auth/providers/bcrypt-provider.ts, backend/src/auth/providers/hashing-provider.ts, backend/src/leaderboard/entities/leaderboard.entity.ts, backend/src/result/entities/result.entity.ts, backend/src/result/enums/status.enum.ts, backend/src/users/entities/user.entity.ts, backend/src/users/providers/create-users-provider.ts, backend/src/users/users.controller.ts, backend/src/users/users.module.ts, backend/src/users/users.service.ts, frontend/app/page.js, frontend/components/Keyboard.jsx, frontend/components/Keys.jsx, frontend/package-lock.json, frontend/package.json, onchain/src/dewordle.cairo, onchain/tests/test_dewordle.cairo
implement keyboard display 
closes - #10
=> implement keyboard display

backend/config/contractConfigService.ts, backend/package-lock.json, backend/package.json, package-lock.json
I added the 'contractConfigService.ts' in the config folder which is located in the root of the backend folder. This contract service reads from the .env and can be injected wherever it is needed in the application.
=> feat(config): add .env file handling with ConfigModule

onchain/Scarb.lock, onchain/Scarb.toml, onchain/src/dewordle.cairo, onchain/tests/test_dewordle.cairo
=> feat: Implement Access Control

onchain/.tool-versions, onchain/src/dewordle.cairo, onchain/src/interfaces.cairo, onchain/tests/test_dewordle.cairo
This PR implements submit_guess and adds corresponding tests.
Fixes #30
=> Implement submit_guess

frontend/components/SignUpForm.jsx, frontend/package-lock.json
=> Fixed illustration alignment

frontend/app/(auth)/layout.tsx, frontend/app/(auth)/signin/page.jsx, frontend/components/LandingPage.jsx
=> fix routing issue

backend/src/users/entities/user.entity.ts, backend/src/users/users.controller.ts, backend/src/users/users.service.ts
I have now created:
Find All Users (with pagination) endpoints and Soft Delete a User
=> implementation of Find All Users &  Delete User

backend/src/users/dto/update-user.dto.ts, backend/src/users/users.controller.ts, backend/src/users/users.service.ts
Update user endpoint and dto
close issue #99
=> update user dto and endpoint

backend/src/common/exceptions/database-error.exception.ts, backend/src/leaderboard/dto/update-leaderboard.dto.ts, backend/src/leaderboard/leaderboard.controller.ts, backend/src/leaderboard/leaderboard.module.ts, backend/src/leaderboard/leaderboard.service.ts, backend/src/result/entities/result.entity.ts, backend/src/users/entities/user.entity.ts, backend/src/users/providers/create-users-provider.ts, backend/src/users/users.module.ts
=> update leaderboard endpoint

backend/package-lock.json, backend/src/admin/admin.service.ts, backend/src/admin/dto/update-admin.dto.ts
I have finished the task assigned to me
=> First commit on this branch

backend/src/admin/admin.module.ts
=> resolve exception handler error

backend/src/admin/admin.module.ts
=> remove duplicate identifier

frontend/app/(auth)/change-password/page.jsx, frontend/components/ChangePassword.jsx
closes #185 
- Created a page in the `(auth)/change-password/page.jsx`
- created a component called `ChangePassword.jsx`
- created a form that takes in the following: existing password, new password and re-enter password.
- ensured the continue button is disabled till all form fields are filled.
- ensured responsiveness across devices.
=> Feat:change password page

backend/package-lock.json, backend/src/app.module.ts, backend/src/common/example.ts, backend/src/common/exceptions/index.ts, backend/src/common/filters/all-exceptions.filter.ts, backend/src/common/filters/auth-exception.filter.ts, backend/src/common/filters/blockchain-exception.filter.ts, backend/src/common/filters/database-exception.filter.ts, backend/src/common/filters/index.ts, backend/src/common/filters/session-exception.filter.ts, backend/src/common/filters/validation-exception.filter.ts, backend/src/common/interfaces/error-response.interface.ts, backend/src/main.ts
=> "feat: exception handler and custom error handling"

backend/src/reward-resource/reward.controller.ts, backend/src/reward-resource/reward.entity.ts, backend/src/reward-resource/reward.module.ts, backend/src/reward-resource/reward.service.ts
=> Reward resource and all it's utilities

backend/package-lock.json, backend/src/search/dto/auto-suggestion.dto/auto-suggestion.dto.ts, backend/src/search/dto/repositories/search.reository.spec.ts, backend/src/search/dto/repositories/search.repository/search.contorller.spec.ts, backend/src/search/dto/repositories/search.repository/search.controller.ts, backend/src/search/dto/repositories/search.repository/search.module.ts, backend/src/search/dto/repositories/search.repository/search.repository.ts, backend/src/search/dto/repositories/search.repository/search.service.ts, backend/src/search/dto/search-query.dto/search-query.dto.spec.ts, backend/src/search/dto/search-query.dto/search-query.dto.ts, backend/src/search/dto/search-result.dto/search-result.dto.spec.ts, backend/src/search/dto/search-result.dto/search-result.dto.ts, backend/src/search/dto/trending-search.dto/trending-search.dto.ts
=> feat: Implement search resource and module

frontend/app/(root)/profile/page.jsx, frontend/components/Profile.jsx, frontend/next.config.mjs
=> feat: Build user profile page

frontend/app/(root)/forgot-password/page.tsx, frontend/components/ForgotPassword.jsx, frontend/utils/schema/forgotPasswordSchema.ts
Created the forgot password component, and added the import into the forgot password page.
Handled form validation and made sure button is disabled until a valid email is entered.
Also added error message field for invalid or empty emails
=> Implemented Forgot password page UI

backend/src/guest/guest.controller.ts, backend/src/guest/guest.service.ts, backend/src/guest/provider/redis.service.ts
Reverts Lead-Studios/DeWordle#229
=> Revert "feat: added update guest endpoint and fetch result endpoint"

backend/src/guest/guest.controller.ts, backend/src/guest/guest.service.ts, backend/src/guest/provider/redis.service.ts
Reverts Lead-Studios/DeWordle#232
=> Revert "Revert "feat: added update guest endpoint and fetch result endpoint""

frontend/app/(root)/coming-soon/page.jsx, frontend/components/ComingSoon.jsx, frontend/package-lock.json
=> coming soon feature

frontend/app/(root)/interactive-how-to-play/page.jsx, frontend/components/InteractiveHowToPlay.jsx
=> fixed the interactive how to play

frontend/app/(root)/achievements/page.jsx, frontend/components/Achievements.jsx
Description
This PR introduces a new "Achievement" component, designed to display key accomplishments or metrics in a visually appealing manner. It includes basic styling and prop-based content rendering.
Related Issue
Closes #456
Type of Change
[x] New feature (non-breaking change which adds functionality)
Checklist
[x] I have read the CONTRIBUTING document.
[x] My code follows the code style of this project.
[x] I have commented my code, particularly in hard-to-understand areas.
[x] I have made corresponding changes to the documentation.
[x] My changes generate no new warnings.
[x] I have added tests that prove my fix is effective or that my feature works.
[x] New and existing unit tests pass locally with my changes.
[ ] Any dependent changes have been merged and published in downstream …
=> fixed the achievements component

backend/src/leadership/contribution-leaderboard.module.ts, backend/src/leadership/controllers/contribution-leaderboard.controller.ts, backend/src/leadership/dto/create-contribution.dto.ts, backend/src/leadership/dto/get-leaderboard.dto.ts, backend/src/leadership/dto/leaderboard-entry.dto.ts, backend/src/leadership/dto/leaderboard-response.dto.ts, backend/src/leadership/dto/pagination.dto.ts, backend/src/leadership/entities/achievement.entity.ts, backend/src/leadership/entities/contribution-type.entity.ts, backend/src/leadership/entities/contribution.entity.ts, backend/src/leadership/entities/user-achievement.entity.ts, backend/src/leadership/entities/user-contribution.entity.ts, backend/src/leadership/enums/contribution-type.enum.ts, backend/src/leadership/enums/time-range.enum.ts, backend/src/leadership/events/contribution-event.emitter.ts, backend/src/leadership/events/contribution-event.listener.ts, backend/src/leadership/repositories/achievement.repository.ts, backend/src/leadership/repositories/contribution-type.repository.ts, backend/src/leadership/repositories/contribution.repository.ts, backend/src/leadership/repositories/user-achievement.repository.ts, backend/src/leadership/repositories/user-contribution.repository.ts, backend/src/leadership/services/contribution-achievement.service.ts, backend/src/leadership/services/contribution-cache.service.ts, backend/src/leadership/services/contribution-leaderboard.service.ts, backend/src/leadership/services/contribution-logger.service.ts, backend/src/leadership/services/contribution-metrics.service.ts, backend/src/leadership/services/contribution-scheduler.service.ts, backend/src/leadership/services/contribution-validation.service.ts, backend/src/leadership/services/contribution.service.ts, backend/src/leadership/services/user-contribution.service.ts
closes #195 
Created the leadership resource
#195  
- [X ] New feature (non-breaking change which adds functionality)
=> added contribution leadership endpoints

frontend/components/SubAdminSignInForm.jsx
I integrated the Sub Admin Sign In page and made the sign in button have two distinct states
Closes #237
=> feat:added SubAdmin SignIn page

frontend/app/not-found.js
Implemented the page-not-found (404 page)
Closes #262 
Screenrecord: https://www.loom.com/share/6f0a3cccf2004ac691a6a073950729d7?sid=5e6c39f9-0666-430c-8091-5f85ba5c5d6f
=> FEAT: Implemented the 404 page

frontend/app/(root)/reset-password/page.jsx, frontend/components/ResetPassword.jsx
closes-[#270]
This PR updates the reset-password page.
I made use of useeffect to check if the passwords match each time any of the passwords value changes. When it does, I update a state. 
below is a screenshot of .....
when passwords does not match.
and..
when passwords match
=> completed the reset password form and validation

onchain/src/contracts/dewordle.cairo, onchain/src/interfaces.cairo, onchain/tests/test_dewordle.cairo
=> refac + add docstrings

backend/src/app.module.ts
update app module to connect backend to render and neon db
=> update: update app module

backend/.env.example, backend/src/auth/auth.module.ts, backend/src/auth/entities/token.entity.ts, backend/src/auth/enums/token-type.enum.ts, backend/src/auth/providers/auth.service.ts, backend/src/auth/providers/sign-in.provider.ts, backend/src/auth/providers/token.services.ts, backend/src/leaderboard/dto/create-leaderboard.dto.ts, backend/src/leaderboard/entities/leaderboard.entity.ts, backend/src/mail/providers/mail.service.ts, backend/src/main.ts, backend/src/result/dto/create-result.dto.ts, backend/src/result/entities/result.entity.ts, backend/src/result/enums/status.enum.ts, backend/src/result/result.service.ts, backend/src/users/dto/create-user.dto.ts, backend/src/users/entities/user.entity.ts, backend/src/users/providers/create-users-provider.ts, backend/src/users/users.controller.ts, backend/src/users/users.service.ts
This PR sets up Neon DB and integrates authentication, enabling Sign Up and Sign In functionalities. Users can now be created and authenticated via the implemented auth endpoints. The created users will be stored in the Neon database and can be retrieved during login.
Fixes #294 
N/A
N/A
N/A
=> feat: setup Neon DB and implement auth (Sign In & Sign Up)

backend/package-lock.json, backend/package.json, backend/src/auth/enums/token-type.enum.ts, backend/src/auth/providers/auth.service.ts, backend/src/auth/providers/sign-in.provider.ts, backend/src/auth/providers/token.services.ts, backend/src/sub-admin/sub-admin.controller.spec.ts, frontend/app/hooks/useSignIn.js, frontend/app/layout.jsx, frontend/app/providers/QueryProvider.js, frontend/app/providers/index.js, frontend/components/SignInForm.jsx, frontend/components/SignUpForm.jsx, frontend/components/sigInWithGoogle.jsx, frontend/utils/axios.js
=> Integrated sigin endpoint using axios

frontend/app/(root)/dewordle/page.jsx, frontend/app/(root)/game/page.tsx, frontend/app/layout.jsx, frontend/app/providers/QueryProvider.js, frontend/components/AdminSignin.jsx, frontend/components/DeWordle.jsx, frontend/components/DeWordleLogo.jsx, frontend/components/DewordleOnboardingNavbar.jsx, frontend/components/LandingPage.jsx, frontend/components/LandingPageNavbar.jsx, frontend/components/footer.jsx
This PR implements a **dynamic navbar setup** and **global footer inclusion** for the DeWordle application.  
- Introduced a **dedicated navbar for the landing page** (`LandingNavbar.tsx`).  
- Renamed `NavbarLandingpage.tsx` → `DewordleNavbar.tsx`.  
- Ensured `Layout.tsx` dynamically renders the correct navbar based on the page path.  
- Integrated `Footer.tsx` globally, **excluding authentication pages** (`/sign-in`, `/sign-up`).  
- Verified styling consistency and responsiveness.  
---
Closes #304 
---
---
---
**📌 Landing Page Navbar:**  
- Screenshot of `LandingNavbar.tsx` in action.  
**📌 Dewordle Game Page Navbar:**  
- Screenshot of `DewordleNavbar.tsx` rendering correctly.  
- 
**📌 Footer Visibility:**  
- Screenshot of `Footer.tsx` appearing globally except on auth pages.  
- …
=> Feat: Implement Dynanmic Nav & Global footer

frontend/app/hooks/useSignIn.js, frontend/app/hooks/useSignup.js, frontend/app/layout.jsx, frontend/components/SignInForm.jsx, frontend/components/SignUpForm.jsx, frontend/package-lock.json, frontend/package.json
…cess
305 
This PR adds a user feedback mechanism using React Toast notifications to confirm successful account creation and login. This improves the user experience by providing instant, clear feedback for these actions.
Closes: #305 
- Installed and integrated react-toastify for toast notifications (if not already available).
- Added a success toast message for account creation: "Account created successfully!".
- Added a success toast message for signIn: "Sign in successful!".
- Added an error toast message for signIn and signUp: "Something went wrong. Please try again."
=> Implement React Toast Notification for Account Creation and Login Success

frontend/components/playourgame.jsx
Updated the play game now to link to Dewordle's onboarding screen rather than directly linking to the game.
CLOSES #326
=> Update link to route to onboardPage

frontend/app/layout.jsx
This PR fixes the issue where the landing page navbar appears on unintended routes.
Closes #332
N/A
N/A
=> fix: navbar unintended routes

frontend/app/(root)/page.jsx, frontend/components/ui/LandingPageSkeletonLoader.tsx
This pull request introduces a skeletal layout loader for the landing page, enhancing user experience during content loading by providing a visual placeholder that mimics the final page design.
- Fully responsive skeletal loader matching the landing page layout
- Smooth, non-intrusive loading transition
- Works seamlessly across desktop and mobile platforms
- Prevents layout shifts during content loading
- Implemented using React and Tailwind CSS
- Uses `animate-pulse` for subtle loading animation
- Responsive grid layout matching original design
- Minimal performance overhead
- Added `LandingPageSkeletonLoader.tsx` component
- Updated `page.tsx` to integrate skeleton loader
- Implemented loading state management
https://www.loom.com/share/3b262598a95b4351860aed9234e0bba2?t=34&sid=bcf53032 …
=> Implement Skeletal Layout Loader for Landing Page #303

frontend/app/(root)/accomplishments/page.jsx, frontend/components/Accomplishments.jsx
implementation of streak-accomplishments-system
- [x ] New feature (non-breaking change which adds functionality)
=> implementation of streak-accomplishments-system

frontend/app/(root)/layout.js, frontend/app/layout.jsx, frontend/components/SpellingBee.jsx, frontend/components/SpellingBeeHeader.tsx, frontend/components/playourgame.jsx
This PR fixes some inconsistent styling
Closes  #346 
N/A
N/A
N/A
=> fix: remove double header and adjust styling

frontend/components/Keyboard.jsx, frontend/components/WordGrid.jsx, frontend/context/AppContext.jsx
This PR integrates the getWordHook and uses it in the keyboard and word grid 
Closes #338 
N/A
N/A
N/A
=> feat: implement word guess game

frontend/components/SignUpForm.jsx, frontend/package-lock.json, frontend/package.json
i fixed double "Already have an account? Sign in" and "Already have an account? Log In" in signup.tsx
Fixes #334
=> fixed double login button

frontend/app/(root)/modes/page.jsx, frontend/app/layout.jsx, frontend/components/GameCard.jsx, frontend/components/How-to-play.jsx, frontend/components/TrendingGames.jsx, frontend/components/playourgame.jsx
This PR implements the changes required for [[Issue #352](https://github.com/Lead-Studios/DeWordle/issues/352)](https://github.com/Lead-Studios/DeWordle/issues/352). It improves the game’s word-checking logic to ensure players receive accurate feedback when guessing words. The update enhances the user experience by refining how correct and incorrect guesses are displayed.  
Closes [[#352](https://github.com/Lead-Studios/DeWordle/issues/352)](https://github.com/Lead-Studios/DeWordle/issues/352)  
https://github.com/user-attachments/assets/a46ed4f8-7e86-4525-916a-e0288d20548b
This fix ensures that word validations follow the expected logic, preventing incorrect word classifications.  
1. Start a new game in DeWordle.  
2. Enter valid and invalid words and observe how feedback is displayed. …
=> Implement Modes and Animated how to play.

onchain/src/constants.cairo, onchain/src/contracts/dewordle.cairo, onchain/src/interfaces.cairo, onchain/tests/test_dewordle.cairo, onchain/tests/test_utils.cairo
Implemented  a streak tracking system that records and updates a user's daily progress. The system should ensure that users who correctly guess the word of the day correctly on consecutive days maintain a streak, while missing a day resets their current streak. Additionally, the maximum streak a user has achieved should also be tracked.
Closes #97
=> [ Feat ]: Implement Daily Streak Tracking

frontend/app/(root)/modes/page.jsx, frontend/components/PracticeMode.jsx
This PR addresses [[Issue #353](https://github.com/Lead-Studios/DeWordle/issues/353)](https://github.com/Lead-Studios/DeWordle/issues/353) by enhancing the game's UI responsiveness. The update ensures a smoother and more engaging experience across different screen sizes, fixing layout inconsistencies and improving accessibility.  
Closes [[#353](https://github.com/Lead-Studios/DeWordle/issues/353)](https://github.com/Lead-Studios/DeWordle/issues/353)  
This fix improves game responsiveness on both desktop and mobile, ensuring the layout remains consistent and easy to interact with on various screen sizes.  
1. Open DeWordle on different screen sizes (mobile, tablet, and desktop).  
2. Ensure that the game layout adjusts correctly without any UI distortions.  
3. Verify that buttons, text, …
=> Implement Spelling bee Practice Mode

frontend/app/(root)/modes/page.jsx, frontend/components/DailyChallenge.jsx
Here’s the filled-out pull request template for the [[Daily Challenge Feature](https://github.com/Lead-Studios/DeWordle/compare/main...JoeX17:DeWordle:feat/DailyChallenge?expand=1)](https://github.com/Lead-Studios/DeWordle/compare/main...JoeX17:DeWordle:feat/DailyChallenge?expand=1):  
---
This PR introduces the **Daily Challenge** feature, allowing players to participate in a new word challenge each day. The challenge resets daily, providing a fresh puzzle for all users. This update enhances player engagement and encourages daily interaction with the game.  
Closes **#DailyChallengeFeature** (If there's a specific issue, link it here)  
- The Daily Challenge resets at **midnight UTC** every day.  
- Users can only attempt the challenge **once per day**.  
- The game ensures fairness by …
=> Implement spelling bee daily challenge

frontend/.env.example, frontend/app/hooks/useSignIn.js, frontend/components/Navbar.jsx, frontend/context/AppContext.jsx
This PR introduces changes to persist user data using the Context API and display the logged-in user's username on the /game route. After a successful sign-in, the user data is stored in the context and in localStorage, ensuring that the username (and other details) is accessible across components. This provides immediate feedback to users that they are logged in, enhancing the overall user experience.
Closes #330
https://github.com/user-attachments/assets/c8c197a5-f3a3-4552-bdb4-05dd973c9f10
- The PR ensures that if no user is logged in, the Navbar defaults to showing a "Guest" message or similar prompt.
-The user data is read from localStorage on application load and then stored in Context via the AppProvider, ensuring centralized state management.
-All changes are in line with the …
=> Persist user data in Context API and display username on /game route

backend/src/pricing/dto/calculate-price.dto.ts, backend/src/pricing/dto/create-discount-code.dto.ts, backend/src/pricing/dto/create-pricing-rule.dto.ts, backend/src/pricing/dto/create-pricing-tier.dto.ts, backend/src/pricing/dto/validate-discount-code.dto.ts, backend/src/pricing/entities/discount-code.entity.ts, backend/src/pricing/entities/pricing-rule.entity.ts, backend/src/pricing/entities/pricing-tier.entity.ts, backend/src/pricing/pricing.controller.ts, backend/src/pricing/pricing.module.ts, backend/src/pricing/pricing.service.ts
implemented multi tier system for Dewordle
CLOSES #368
=> implement multi tier

onchain/src/contracts/dewordle.cairo, onchain/src/utils.cairo, onchain/tests/test_dewordle.cairo
issue #235 
Updated the set_daily_word function as per the requirement and also wrote the tests
=> set_daily_word updated and tests written

onchain/src/contracts/dewordle.cairo, onchain/src/interfaces.cairo, onchain/tests/test_dewordle.cairo
=> streak tracking + refac

frontend/components/SignInForm.jsx
=> fix:update route

frontend/components/DeWordle.jsx, frontend/components/DewordleOnboardingNavbar.jsx, frontend/components/Navbar.jsx
=> remove modal from dewordle-onboard navbar

frontend/components/LandingPageNavbar.jsx, frontend/components/Navbar.jsx
=> add profile dropdown to landing page

backend/src/app.module.ts, backend/src/main.ts, backend/src/words/words.controller.ts, frontend/app/hooks/useGetWord.js
=> fix: fix word guess api

onchain/src/contracts/erc20.cairo, onchain/src/interfaces.cairo, onchain/src/lib.cairo, onchain/tests/test_erc20.cairo
Closes #400 
This PR implements a fully functional, secure, and optimized ERC-20 token contract for the DeWordle project on StarkNet. It introduces the complete ERC-20 standard functionality, including transfer, approval, and minting capabilities, while adhering to best practices for Cairo 1.0 development.
- Created the `DeWordleToken` contract with all required ERC-20 functionality
- Implemented the IERC20 interface in `interfaces.cairo`
- Added complete test coverage in `test_erc20.cairo`
- Updated project structure to include the new ERC-20 module
The contract stores:
- Token balances using a Map of ContractAddress to u256
- Allowances using a Map of (owner, spender) tuples to u256 values
- Token metadata including name, symbol, decimals, and total supply
- Contract owner address
- …
=> Implement ERC-20 Token Contract for DeWordle

backend/src/games/games.module.ts, backend/src/games/spelling-bee/spelling-bee.controller.ts, backend/src/games/spelling-bee/spelling-bee.module.ts, backend/src/games/spelling-bee/spelling-bee.service.ts
Added the Spelling Bee module under the games domain
Closes  #394
=> feat: add spelling-bee module under games domain

backend/src/app.module.ts, backend/src/games/games.controller.spec.ts, backend/src/games/games.controller.ts, backend/src/games/games.module.ts, backend/src/games/lettered-box/dto/create-lettered-box.dto.ts, backend/src/games/lettered-box/dto/update-lettered-box.dto.ts, backend/src/games/lettered-box/entities/lettered-box.entity.ts, backend/src/games/lettered-box/lettered-box.controller.spec.ts, backend/src/games/lettered-box/lettered-box.controller.ts, backend/src/games/lettered-box/lettered-box.module.ts, backend/src/games/lettered-box/lettered-box.service.spec.ts, backend/src/games/lettered-box/lettered-box.service.ts
Set up the foundational module structure for the new game Lettered Box, in our multi-game puzzle backend. This is a boilerplate setup with no business logic — only module, controller, and service scaffolding.
closes #406
=> scaffold lettered-box module

backend/package-lock.json, backend/package.json, backend/src/games/lettered-box/dto/create-lettered-box.dto.ts, backend/src/games/lettered-box/dto/submit-solution-dto.ts, backend/src/games/lettered-box/entities/lettered-box.entity.ts, backend/src/games/lettered-box/lettered-box.module.ts
Define DTO's and entity for lettered box game
Closes #408 
N/A
N/A
N/A
=> define dto's and entity for lettered box game

backend/src/games/games.module.ts, backend/src/games/hangman/hangman.controller.spec.ts, backend/src/games/hangman/hangman.controller.ts, backend/src/games/hangman/hangman.module.ts, backend/src/games/hangman/hangman.service.spec.ts, backend/src/games/hangman/hangman.service.ts, backend/src/games/hangman/score/controllers/score.controller.spec.ts, backend/src/games/hangman/score/controllers/score.controller.ts, backend/src/games/hangman/score/dto/create-score.dto.ts, backend/src/games/hangman/score/dto/index.ts, backend/src/games/hangman/score/dto/leaderboard-query.dto.ts, backend/src/games/hangman/score/dto/statistics-query.dto.ts, backend/src/games/hangman/score/dto/update-score.dto.ts, backend/src/games/hangman/score/entities/score.entity.ts, backend/src/games/hangman/score/enums/timeFrame.enum.ts, backend/src/games/hangman/score/http/score.test.http, backend/src/games/hangman/score/interfaces/leaderboardEntry.interface.ts, backend/src/games/hangman/score/interfaces/leaderboardResponse.interface.ts, backend/src/games/hangman/score/interfaces/statistics.interface.ts, backend/src/games/hangman/score/providers/leaderboard.service.ts, backend/src/games/hangman/score/providers/score.service.spec.ts, backend/src/games/hangman/score/providers/score.service.ts, backend/src/games/hangman/score/providers/statistics.service.ts, backend/src/games/hangman/score/providers/validation.service.ts, backend/src/games/hangman/score/score.module.ts
This PR implements a comprehensive enhancement to the **Score** module, adding support for detailed score tracking, statistics, and leaderboards. These features aim to boost player engagement and introduce competitive elements into the game environment.
Closes #123 - Implement enhanced score tracking and leaderboards
This enhancement introduces several new API endpoints, score validation logic, and statistical aggregation to better reflect player performance and provide meaningful insights.
1. Use the provided HTTPyac test file to verify all endpoints.
2. Validate leaderboard functionality with various filters and pagination.
3. Submit multiple scores and verify anti-cheating validations.
4. Use admin routes to flag/verify scores and ensure moderation works as expected.
---
**Overview of …
=> BACKEND: Implement Score Tracking and Leaderboards

backend/src/games/games.module.ts, backend/src/games/spelling-bee/dto/puzzal.dto.ts, backend/src/games/spelling-bee/services/PuzzleGenerator.service.spec.ts, backend/src/games/spelling-bee/services/PuzzleGenerator.service.ts
-  Close #397
Generated puzzles by selecting pangram seed words and building a valid word list around them.
=> feat: implement puzzle generator from pangram selection and letter rules

README.md
=> chore: the link to the license did not work

backend/security/decorators/roles.decorator.ts, backend/src/common/enums/users-roles.enum.ts, backend/src/games/hangman/hangman.module.ts, backend/src/games/hangman/words/words.controller.ts, backend/src/games/hangman/words/words.service.ts, package-lock.json
=> Implemented Word Categories in Words Module in HangMan Game

frontend/app/(hangman)/onboard-hangman/page.jsx, frontend/app/(root)/page.jsx, frontend/components/organism/games/Hangman/HangmanOnboarding.jsx, frontend/components/organism/landing-page/HangManSection.jsx, frontend/package-lock.json, frontend/package.json
**Pull Request Title:**
Implemented Landing Page, Onboarding Flow with Animation, and Fixed Confetti Module Error
---
**Linked Issue:**  
Closes #427 
---
This PR completes the implementation of the **landing page** and **onboarding screens** for the DeWordle Hangman scaffold. It also includes:
- ✅ A fully animated onboarding experience using `framer-motion`
- ✅ Integration of the `canvas-confetti` package to handle visual celebration effects
- ✅ Fix for the missing `canvas-confetti` module error (`Module not found: Can't resolve 'canvas-confetti'`)
---
- **Landing Page UI**: Responsive and themed to match the DeWordle design language.
- **Onboarding Flow**: Includes transitions between steps and engaging motion effects.
- **Confetti Fix**: Installed `canvas-confetti` and tested …
=> feat: Build hangman and onboarding screen

frontend/app/(hangman)/hangman/page.jsx, frontend/components/organism/games/Hangman/Hangman.jsx, frontend/components/organism/games/Hangman/HangmanOnboarding.jsx, frontend/components/organism/games/Hangman/game-over-modal.jsx, frontend/components/organism/games/Hangman/hangman-drawing.jsx, frontend/components/organism/games/Hangman/keyboard.jsx, frontend/components/organism/games/Hangman/word-display.jsx, frontend/components/organism/landing-page/ArgentInvisibleWalletConnect.tsx, frontend/components/organism/landing-page/LandingPageNavbar.jsx, frontend/components/ui/badge.jsx, frontend/components/ui/button.jsx, frontend/components/ui/tooltip.jsx, frontend/context/AppContext.jsx, frontend/package-lock.json, frontend/package.json, frontend/tsconfig.json
Implement Hang man game interface and functionality
This pr introduces the hangman game interface and also list of words and categories that mirrors the backend, and when the , also it provides a modal for win and loss.
closes #429 
-  [x] I have made corresponding changes to the documentation.
=> feat: implement hangman game interface and win or loss func

backend/package-lock.json, backend/package.json, backend/src/games/dewordle/leaderboard/dto/create-leaderboard.dto.ts, backend/src/games/dewordle/leaderboard/entities/leaderboard.entity.ts, backend/src/games/dewordle/leaderboard/leaderboard.controller.ts, backend/src/games/dewordle/leaderboard/leaderboard.service.ts
=> Implemented Leaderboard - Fetch User Game Scores & Rankings

backend/src/puzzle/dto/validate-word.dto.ts, backend/src/puzzle/entities/puzzle-session.entity.ts, backend/src/puzzle/puzzle.controller.spec.ts, backend/src/puzzle/puzzle.controller.ts, backend/src/puzzle/puzzle.module.ts, backend/src/puzzle/puzzle.service.spec.ts, backend/src/puzzle/puzzle.service.ts
=> Create Endpoint to Validate a User's Word Guess and Update Puzzle Session Progress

backend/src/games/dewordle/dewordle.module.ts, backend/src/puzzle/dto/create-puzzle.dto.ts, backend/src/puzzle/puzzle.controller.ts, backend/src/puzzle/puzzle.module.ts, backend/src/puzzle/puzzle.service.ts, backend/src/puzzle/validators/date-unique.validator.ts, backend/src/puzzle/validators/feature-date.validator.ts, backend/src/puzzle/validators/grid.validator.ts, backend/src/puzzle/validators/spangram.validator.ts, backend/src/puzzle/validators/valid-words.validator.ts
This PR implements a secure API endpoint that allows admins to upload new puzzles to the system with comprehensive validation to ensure data integrity and consistency.
Closes: #457
=> feat: Secure Admin Puzzle Upload Endpoint with Comprehensive Validation
